version: '3'
services:
  dev:
    build: .
    links:
      - mysql
    ports:
      - 8080:80
    expose:
      - "80" 
    volumes:
      - "./html:/var/www/html"
    environment:
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress

  mysql:
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    expose:
      - "3306"
    volumes:
      - "mariadb_datadir:/var/lib/mysql"
volumes: 
  mariadb_datadir: